# Generated by Django 4.2.1 on 2023-05-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['licence_plate'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['year', 'id'], 'verbose_name': 'car model', 'verbose_name_plural': 'car models'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date', 'id'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderlist',
            options={'verbose_name': 'order list', 'verbose_name_plural': 'order lists'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name', 'id'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_model_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='car_id',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='service_id',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='service.carmodel', verbose_name='model'),
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.car', verbose_name='car'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lists', to='service.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lists', to='service.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
