# Generated by Django 4.2.1 on 2023-05-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['year'], 'verbose_name': 'car model', 'verbose_name_plural': 'car models'},
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Price'),
        ),
    ]
