# Generated by Django 4.2.1 on 2023-05-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_carmodel_options_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantity')),
                ('price', models.CharField(max_length=50, verbose_name='Price')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='service.order', verbose_name='order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='service.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'order entry',
                'verbose_name_plural': 'order entries',
            },
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
