# Generated by Django 4.2.1 on 2023-05-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=18, null=True, verbose_name='Price'),
        ),
    ]
