# Generated by Django 4.2.1 on 2023-05-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'Reserved'), (2, 'Taken'), (3, 'Unavailable'), (7, 'Broken')], db_index=True, default=0, verbose_name='status'),
        ),
    ]
