# Generated by Django 4.2.1 on 2023-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_order_status_orderentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
