# Generated by Django 4.2.1 on 2023-06-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_car_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='cover',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='service/car_covers'),
        ),
    ]
