# Generated by Django 4.2.1 on 2023-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.CharField(max_length=50, verbose_name='Customer'),
        ),
    ]
