# Generated by Django 4.2.1 on 2023-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_remove_car_customer_car_client_car_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='due_back',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='due back'),
        ),
    ]
