# Generated by Django 4.2.1 on 2023-06-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_remove_order_due_back_orderentry_due_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderentry',
            name='due_back',
        ),
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='due back'),
        ),
    ]
