# Generated by Django 4.2.1 on 2023-06-06 09:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_remove_orderentry_due_back_order_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='note',
            field=tinymce.models.HTMLField(blank=True, max_length=8000, null=True, verbose_name='Note'),
        ),
    ]
