# Generated by Django 4.2.1 on 2023-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_orderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Price'),
        ),
    ]
